export const ErrorCodes = {
    INTERNAL_SERVER_ERROR: { code: "internal-server-error", status: 500 },
    TOKEN_NOT_FOUND: { code: "token-not-found", status: 401 },
    UNAUTHORIZED: { code: "unauthorized", status: 401 },
    INVALID_EMAIL: { code: "invalid-email", status: 400 },
    WRONG_TYPE: { code: "wrong-type", status: 400 },
    WEAK_PASSWORD: { code: "weak-password", status: 400 },
    EMAIL_ALREADY_IN_USE: { code: "email-already-in-use", status: 409 },
    INVALID_CREDENTIAL: { code: "invalid-credential", status: 401 },
    NOT_FOUND: { code: "not-found", status: 404 },
    INVALID_INPUT: { code: "invalid-input", status: 400 },
    ALREADY_EXISTS: { code: "already-exists", status: 409 },
    MISSING_PARAMETERS: { code: "missing-parameters", status: 400 },
    INVALID_PARAMETERS: { code: "invalid-parameters", status: 400 },
    PAYLOAD_TOO_LARGE: { code: "payload-too-large", status: 413 },
    RATE_LIMIT_EXCEEDED: { code: "rate-limit-exceeded", status: 429 },
    FORBIDDEN: { code: "forbidden", status: 403 },
    RESOURCE_LOCKED: { code: "resource-locked", status: 423 },
    CONFLICT: { code: "conflict", status: 409 },
    SERVICE_UNAVAILABLE: { code: "service-unavailable", status: 503 },
    DATABASE_ERROR: { code: "database-error", status: 500 },
    TIMEOUT: { code: "timeout", status: 504 },
    UNSUPPORTED_OPERATION: { code: "unsupported-operation", status: 400 },
    DUPLICATE_REQUEST: { code: "duplicate-request", status: 409 },
    EXPIRED_TOKEN: { code: "expired-token", status: 401 },
};

export const SuccessCodes = {
    OK: { code: "ok", status: 200 },
    CREATED: { code: "created", status: 201 },
    ACCEPTED: { code: "accepted", status: 202 },
    NO_CONTENT: { code: "no-content", status: 204 },
    RESET_CONTENT: { code: "reset-content", status: 205 },
    PARTIAL_CONTENT: { code: "partial-content", status: 206 },
    MULTI_STATUS: { code: "multi-status", status: 207 },
    ALREADY_REPORTED: { code: "already-reported", status: 208 },
    IM_USED: { code: "im-used", status: 226 },
};
